# -*- coding: utf-8 -*-
"""ChurnAnalysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o67_ep47tDMb9lGeDm0vbYLb5WsR6pGJ
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

df=pd.read_csv('/content/Customer-Churn-analysis/Customer Churn.csv')
df

df.info()

"""replacing blank values(considered as object datatype) into 0 and changing datatype"""

df['TotalCharges']=df['TotalCharges'].replace(" " , "0")
df['TotalCharges']=df['TotalCharges'].astype("float")

df.info()

df.isnull().sum()

df.describe()

"""to check if there is duplicated row or not

"""

df.duplicated()

df.duplicated().sum()

df['customerID'].duplicated().sum()

"""converting the seniorcitizen data into yes/no value >>> easier to understand

"""

def conv(value):
  if value==1:
    return "yes"
  else:
      return "no"

df["SeniorCitizen"]=df["SeniorCitizen"].apply(conv)

df.head()

a=sns.countplot(x='Churn',data=df)
a.bar_label(a.containers[0])
plt.title("Count By Churn")
plt.show()

a=sns.countplot(x='gender',data=df,hue="Churn")
a.bar_label(a.containers[0])
a.bar_label(a.containers[1])
plt.title("Count by Gender")
plt.show()

a=sns.countplot(x='SeniorCitizen',data=df,hue="Churn")
a.bar_label(a.containers[0])
a.bar_label(a.containers[1])
plt.title("Count by SeniorCitizen")
plt.show()

sns.histplot(x="tenure", data=df,bins=72,hue="Churn")
plt.show()

"""people who used the services for 1 or 2 months have churned while those who used it for long term have not left"""

a=sns.countplot(x='Contract',data=df,hue="Churn")
a.bar_label(a.containers[0])
plt.title("Count By Contract")
plt.show()

"""people having month to month contract are likely to churn"""

df.columns.values

"""used ai  to create rest of the plots."""

# Select categorical columns (excluding customerID & Churn)
cat_cols = [

    'PhoneService', 'MultipleLines', 'InternetService',
    'OnlineSecurity', 'OnlineBackup', 'DeviceProtection',
    'TechSupport', 'StreamingTV', 'StreamingMovies',
    'Contract', 'PaperlessBilling', 'PaymentMethod'
]

# Set subplot size
plt.figure(figsize=(20, 25))

for i, col in enumerate(cat_cols):
    plt.subplot(6, 3, i+1)
    ax = sns.countplot(x=col, data=df, hue="Churn")
    plt.title(col)
    plt.xticks(rotation=45)

    # Add labels
    for container in ax.containers:
        ax.bar_label(container, padding=1)

plt.tight_layout()
plt.show()

"""these charts show the majority of customers who churn are using>> electronic check,paperless bliing,fibre optics."""



